# fly.toml file generated for spring-violet-4950 on 2023-02-04T21:15:00+05:30

app = "spring-violet-4950"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [[services.ports]]
    port = 9000

[[services]]
  internal_port = 9001
  protocol = "tcp"

  [[services.ports]]
    port = 9001

[[services]]
  internal_port = 9002
  protocol = "tcp"

  [[services.ports]]
    port = 9002

[[services]]
  internal_port = 9004
  protocol = "tcp"

  [[services.ports]]
    port = 9004

[[services]]
  internal_port = 9005
  protocol = "udp"

  [[services.ports]]
    port = 9005
