[package]
name = "budget_chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32" }
protohackers_tcp_helper = { path = "../protohackers_tcp_helper" }
